#![allow(missing_docs)]
//! Bitmask flag constants controlling Senzing engine response content.
//!
//! These constants mirror the C header files `libSzEngineFlags.h` and
//! `libSzEngineFlagGroups.h`. Individual flags can be combined with the
//! bitwise OR operator (`|`) or by using the [`flags`] helper function.
//!
//! Pre-composed flag groups (e.g., [`SZ_ENTITY_DEFAULT_FLAGS`]) provide
//! recommended defaults for common API calls.

/// Combines multiple flag values into a single bitmask.
pub fn flags(flags: &[i64]) -> i64 {
    flags.iter().fold(0, |acc, &f| acc | f)
}

// ---------------------------------------------------------------------------
// No flags
// ---------------------------------------------------------------------------

pub const SZ_NO_FLAGS: i64 = 0;

// ---------------------------------------------------------------------------
// Flags for exporting entity data
// ---------------------------------------------------------------------------

pub const SZ_EXPORT_INCLUDE_MULTI_RECORD_ENTITIES: i64 = 1 << 0;
pub const SZ_EXPORT_INCLUDE_POSSIBLY_SAME: i64 = 1 << 1;
pub const SZ_EXPORT_INCLUDE_POSSIBLY_RELATED: i64 = 1 << 2;
pub const SZ_EXPORT_INCLUDE_NAME_ONLY: i64 = 1 << 3;
pub const SZ_EXPORT_INCLUDE_DISCLOSED: i64 = 1 << 4;
pub const SZ_EXPORT_INCLUDE_SINGLE_RECORD_ENTITIES: i64 = 1 << 5;

pub const SZ_EXPORT_INCLUDE_ALL_ENTITIES: i64 =
    SZ_EXPORT_INCLUDE_MULTI_RECORD_ENTITIES | SZ_EXPORT_INCLUDE_SINGLE_RECORD_ENTITIES;

pub const SZ_EXPORT_INCLUDE_ALL_HAVING_RELATIONSHIPS: i64 = SZ_EXPORT_INCLUDE_POSSIBLY_SAME
    | SZ_EXPORT_INCLUDE_POSSIBLY_RELATED
    | SZ_EXPORT_INCLUDE_NAME_ONLY
    | SZ_EXPORT_INCLUDE_DISCLOSED;

// ---------------------------------------------------------------------------
// Flags for outputting entity relation data
// ---------------------------------------------------------------------------

pub const SZ_ENTITY_INCLUDE_POSSIBLY_SAME_RELATIONS: i64 = 1 << 6;
pub const SZ_ENTITY_INCLUDE_POSSIBLY_RELATED_RELATIONS: i64 = 1 << 7;
pub const SZ_ENTITY_INCLUDE_NAME_ONLY_RELATIONS: i64 = 1 << 8;
pub const SZ_ENTITY_INCLUDE_DISCLOSED_RELATIONS: i64 = 1 << 9;

pub const SZ_ENTITY_INCLUDE_ALL_RELATIONS: i64 = SZ_ENTITY_INCLUDE_POSSIBLY_SAME_RELATIONS
    | SZ_ENTITY_INCLUDE_POSSIBLY_RELATED_RELATIONS
    | SZ_ENTITY_INCLUDE_NAME_ONLY_RELATIONS
    | SZ_ENTITY_INCLUDE_DISCLOSED_RELATIONS;

// ---------------------------------------------------------------------------
// Flags for outputting entity feature data
// ---------------------------------------------------------------------------

pub const SZ_ENTITY_INCLUDE_ALL_FEATURES: i64 = 1 << 10;
pub const SZ_ENTITY_INCLUDE_REPRESENTATIVE_FEATURES: i64 = 1 << 11;

// ---------------------------------------------------------------------------
// Flags for getting extra information about an entity
// ---------------------------------------------------------------------------

pub const SZ_ENTITY_INCLUDE_ENTITY_NAME: i64 = 1 << 12;
pub const SZ_ENTITY_INCLUDE_RECORD_SUMMARY: i64 = 1 << 13;
pub const SZ_ENTITY_INCLUDE_RECORD_DATA: i64 = 1 << 14;
pub const SZ_ENTITY_INCLUDE_RECORD_MATCHING_INFO: i64 = 1 << 15;
pub const SZ_ENTITY_INCLUDE_RECORD_JSON_DATA: i64 = 1 << 16;
pub const SZ_ENTITY_INCLUDE_RECORD_FEATURES: i64 = 1 << 18;
pub const SZ_ENTITY_INCLUDE_RELATED_ENTITY_NAME: i64 = 1 << 19;
pub const SZ_ENTITY_INCLUDE_RELATED_MATCHING_INFO: i64 = 1 << 20;
pub const SZ_ENTITY_INCLUDE_RELATED_RECORD_SUMMARY: i64 = 1 << 21;
pub const SZ_ENTITY_INCLUDE_RELATED_RECORD_DATA: i64 = 1 << 22;
pub const SZ_ENTITY_INCLUDE_INTERNAL_FEATURES: i64 = 1 << 23;
pub const SZ_ENTITY_INCLUDE_FEATURE_STATS: i64 = 1 << 24;
pub const SZ_ENTITY_INCLUDE_RECORD_TYPES: i64 = 1 << 28;
pub const SZ_ENTITY_INCLUDE_RELATED_RECORD_TYPES: i64 = 1 << 29;
pub const SZ_ENTITY_INCLUDE_RECORD_UNMAPPED_DATA: i64 = 1 << 31;
pub const SZ_ENTITY_INCLUDE_RECORD_FEATURE_DETAILS: i64 = 1 << 35;
pub const SZ_ENTITY_INCLUDE_RECORD_FEATURE_STATS: i64 = 1 << 36;
pub const SZ_ENTITY_INCLUDE_RECORD_DATES: i64 = 1 << 39;

// ---------------------------------------------------------------------------
// Flags for finding entity path data
// ---------------------------------------------------------------------------

pub const SZ_FIND_PATH_STRICT_AVOID: i64 = 1 << 25;
pub const SZ_FIND_PATH_INCLUDE_MATCHING_INFO: i64 = 1 << 30;
pub const SZ_FIND_NETWORK_INCLUDE_MATCHING_INFO: i64 = 1 << 33;

// ---------------------------------------------------------------------------
// General flags for including special data
// ---------------------------------------------------------------------------

pub const SZ_INCLUDE_FEATURE_SCORES: i64 = 1 << 26;
pub const SZ_INCLUDE_MATCH_KEY_DETAILS: i64 = 1 << 34;

// ---------------------------------------------------------------------------
// Flags for searching for entities
// ---------------------------------------------------------------------------

pub const SZ_SEARCH_INCLUDE_STATS: i64 = 1 << 27;
pub const SZ_SEARCH_INCLUDE_ALL_CANDIDATES: i64 = 1 << 32;
pub const SZ_SEARCH_INCLUDE_REQUEST: i64 = 1 << 37;
pub const SZ_SEARCH_INCLUDE_REQUEST_DETAILS: i64 = 1 << 38;

pub const SZ_SEARCH_INCLUDE_RESOLVED: i64 = SZ_EXPORT_INCLUDE_MULTI_RECORD_ENTITIES;
pub const SZ_SEARCH_INCLUDE_POSSIBLY_SAME: i64 = SZ_EXPORT_INCLUDE_POSSIBLY_SAME;
pub const SZ_SEARCH_INCLUDE_POSSIBLY_RELATED: i64 = SZ_EXPORT_INCLUDE_POSSIBLY_RELATED;
pub const SZ_SEARCH_INCLUDE_NAME_ONLY: i64 = SZ_EXPORT_INCLUDE_NAME_ONLY;

pub const SZ_SEARCH_INCLUDE_ALL_ENTITIES: i64 = SZ_SEARCH_INCLUDE_RESOLVED
    | SZ_SEARCH_INCLUDE_POSSIBLY_SAME
    | SZ_SEARCH_INCLUDE_POSSIBLY_RELATED
    | SZ_SEARCH_INCLUDE_NAME_ONLY;

// ---------------------------------------------------------------------------
// WithInfo flag
// ---------------------------------------------------------------------------

pub const SZ_WITH_INFO: i64 = 1 << 62;

// ---------------------------------------------------------------------------
// Subgroups (internal groupings used to compose flag groups)
// ---------------------------------------------------------------------------

const SZ_RECORD_FLAGS_SUBGROUP: i64 = SZ_ENTITY_INCLUDE_INTERNAL_FEATURES
    | SZ_ENTITY_INCLUDE_RECORD_FEATURE_DETAILS
    | SZ_ENTITY_INCLUDE_RECORD_FEATURES
    | SZ_ENTITY_INCLUDE_RECORD_FEATURE_STATS
    | SZ_ENTITY_INCLUDE_RECORD_JSON_DATA
    | SZ_ENTITY_INCLUDE_RECORD_DATES
    | SZ_ENTITY_INCLUDE_RECORD_UNMAPPED_DATA;

const SZ_RECORD_PREVIEW_FLAGS_SUBGROUP: i64 = SZ_ENTITY_INCLUDE_INTERNAL_FEATURES
    | SZ_ENTITY_INCLUDE_RECORD_FEATURE_DETAILS
    | SZ_ENTITY_INCLUDE_RECORD_FEATURES
    | SZ_ENTITY_INCLUDE_RECORD_FEATURE_STATS
    | SZ_ENTITY_INCLUDE_RECORD_JSON_DATA
    | SZ_ENTITY_INCLUDE_RECORD_UNMAPPED_DATA;

const SZ_CORE_ENTITY_FLAGS_SUBGROUP: i64 = SZ_ENTITY_INCLUDE_ALL_FEATURES
    | SZ_ENTITY_INCLUDE_REPRESENTATIVE_FEATURES
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_FEATURE_STATS
    | SZ_ENTITY_INCLUDE_RECORD_FEATURES
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY
    | SZ_ENTITY_INCLUDE_RECORD_DATA
    | SZ_ENTITY_INCLUDE_RECORD_MATCHING_INFO
    | SZ_ENTITY_INCLUDE_RECORD_TYPES
    | SZ_RECORD_FLAGS_SUBGROUP;

const SZ_RELATED_ENTITY_FLAGS_SUBGROUP: i64 = SZ_ENTITY_INCLUDE_POSSIBLY_SAME_RELATIONS
    | SZ_ENTITY_INCLUDE_POSSIBLY_RELATED_RELATIONS
    | SZ_ENTITY_INCLUDE_DISCLOSED_RELATIONS
    | SZ_ENTITY_INCLUDE_NAME_ONLY_RELATIONS
    | SZ_ENTITY_INCLUDE_RELATED_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RELATED_MATCHING_INFO
    | SZ_ENTITY_INCLUDE_RELATED_RECORD_DATA
    | SZ_ENTITY_INCLUDE_RELATED_RECORD_SUMMARY
    | SZ_ENTITY_INCLUDE_RELATED_RECORD_TYPES
    | SZ_INCLUDE_MATCH_KEY_DETAILS;

const SZ_SEARCH_HITS_FLAGS_SUBGROUP: i64 = SZ_SEARCH_INCLUDE_RESOLVED
    | SZ_SEARCH_INCLUDE_POSSIBLY_SAME
    | SZ_SEARCH_INCLUDE_POSSIBLY_RELATED
    | SZ_SEARCH_INCLUDE_NAME_ONLY
    | SZ_SEARCH_INCLUDE_ALL_CANDIDATES;

const SZ_SEARCH_CONTENT_FLAGS_SUBGROUP: i64 = SZ_INCLUDE_MATCH_KEY_DETAILS
    | SZ_SEARCH_INCLUDE_REQUEST
    | SZ_SEARCH_INCLUDE_REQUEST_DETAILS
    | SZ_SEARCH_INCLUDE_STATS
    | SZ_INCLUDE_FEATURE_SCORES;

const SZ_WHY_FLAGS_SUBGROUP: i64 =
    SZ_CORE_ENTITY_FLAGS_SUBGROUP | SZ_RELATED_ENTITY_FLAGS_SUBGROUP | SZ_INCLUDE_FEATURE_SCORES;

// ---------------------------------------------------------------------------
// Flag groups by applicability
// ---------------------------------------------------------------------------

pub const SZ_RECORD_FLAGS_GROUP: i64 = SZ_RECORD_FLAGS_SUBGROUP;
pub const SZ_ENTITY_FLAGS_GROUP: i64 =
    SZ_CORE_ENTITY_FLAGS_SUBGROUP | SZ_RELATED_ENTITY_FLAGS_SUBGROUP;
pub const SZ_EXPORT_FLAGS_GROUP: i64 = SZ_EXPORT_INCLUDE_DISCLOSED
    | SZ_EXPORT_INCLUDE_MULTI_RECORD_ENTITIES
    | SZ_EXPORT_INCLUDE_NAME_ONLY
    | SZ_EXPORT_INCLUDE_POSSIBLY_RELATED
    | SZ_EXPORT_INCLUDE_POSSIBLY_SAME
    | SZ_EXPORT_INCLUDE_SINGLE_RECORD_ENTITIES
    | SZ_INCLUDE_MATCH_KEY_DETAILS
    | SZ_ENTITY_FLAGS_GROUP;
pub const SZ_SEARCH_FLAGS_GROUP: i64 =
    SZ_SEARCH_CONTENT_FLAGS_SUBGROUP | SZ_SEARCH_HITS_FLAGS_SUBGROUP | SZ_ENTITY_FLAGS_GROUP;
pub const SZ_FIND_NETWORK_FLAGS_GROUP: i64 =
    SZ_FIND_NETWORK_INCLUDE_MATCHING_INFO | SZ_ENTITY_FLAGS_GROUP;
pub const SZ_FIND_PATH_FLAGS_GROUP: i64 =
    SZ_FIND_PATH_INCLUDE_MATCHING_INFO | SZ_FIND_PATH_STRICT_AVOID | SZ_ENTITY_FLAGS_GROUP;
pub const SZ_WHY_ENTITIES_FLAGS_GROUP: i64 = SZ_WHY_FLAGS_SUBGROUP;
pub const SZ_WHY_RECORDS_FLAGS_GROUP: i64 = SZ_WHY_FLAGS_SUBGROUP;
pub const SZ_WHY_RECORD_IN_ENTITY_FLAGS_GROUP: i64 = SZ_WHY_FLAGS_SUBGROUP;
pub const SZ_WHY_SEARCH_FLAGS_GROUP: i64 =
    SZ_SEARCH_CONTENT_FLAGS_SUBGROUP | SZ_WHY_FLAGS_SUBGROUP | SZ_ENTITY_FLAGS_GROUP;
pub const SZ_HOW_FLAGS_GROUP: i64 = SZ_INCLUDE_FEATURE_SCORES | SZ_INCLUDE_MATCH_KEY_DETAILS;
pub const SZ_VIRTUAL_ENTITY_FLAGS_GROUP: i64 = SZ_CORE_ENTITY_FLAGS_SUBGROUP;
pub const SZ_RECORD_PREVIEW_FLAGS_GROUP: i64 = SZ_RECORD_PREVIEW_FLAGS_SUBGROUP;
pub const SZ_ADD_RECORD_FLAGS_GROUP: i64 = SZ_NO_FLAGS;
pub const SZ_DELETE_RECORD_FLAGS_GROUP: i64 = SZ_NO_FLAGS;
pub const SZ_REEVALUATE_RECORD_FLAGS_GROUP: i64 = SZ_NO_FLAGS;
pub const SZ_REEVALUATE_ENTITY_FLAGS_GROUP: i64 = SZ_NO_FLAGS;
pub const SZ_FIND_INTERESTING_ENTITIES_FLAGS_GROUP: i64 = SZ_NO_FLAGS;

// ---------------------------------------------------------------------------
// Recommended default flags for various API functions
// ---------------------------------------------------------------------------

pub const SZ_RECORD_DEFAULT_FLAGS: i64 = SZ_ENTITY_INCLUDE_RECORD_JSON_DATA;

pub const SZ_ENTITY_CORE_FLAGS: i64 = SZ_ENTITY_INCLUDE_REPRESENTATIVE_FEATURES
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY
    | SZ_ENTITY_INCLUDE_RECORD_DATA
    | SZ_ENTITY_INCLUDE_RECORD_MATCHING_INFO;

pub const SZ_ENTITY_DEFAULT_FLAGS: i64 = SZ_ENTITY_CORE_FLAGS
    | SZ_ENTITY_INCLUDE_ALL_RELATIONS
    | SZ_ENTITY_INCLUDE_RELATED_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RELATED_RECORD_SUMMARY
    | SZ_ENTITY_INCLUDE_RELATED_MATCHING_INFO;

pub const SZ_ENTITY_BRIEF_DEFAULT_FLAGS: i64 = SZ_ENTITY_INCLUDE_RECORD_MATCHING_INFO
    | SZ_ENTITY_INCLUDE_ALL_RELATIONS
    | SZ_ENTITY_INCLUDE_RELATED_MATCHING_INFO;

pub const SZ_EXPORT_DEFAULT_FLAGS: i64 = SZ_EXPORT_INCLUDE_ALL_ENTITIES | SZ_ENTITY_DEFAULT_FLAGS;

pub const SZ_FIND_PATH_DEFAULT_FLAGS: i64 = SZ_FIND_PATH_INCLUDE_MATCHING_INFO
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY;

pub const SZ_FIND_NETWORK_DEFAULT_FLAGS: i64 = SZ_FIND_NETWORK_INCLUDE_MATCHING_INFO
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY;

pub const SZ_WHY_ENTITIES_DEFAULT_FLAGS: i64 = SZ_INCLUDE_FEATURE_SCORES;
pub const SZ_WHY_RECORDS_DEFAULT_FLAGS: i64 = SZ_INCLUDE_FEATURE_SCORES;
pub const SZ_WHY_RECORD_IN_ENTITY_DEFAULT_FLAGS: i64 = SZ_INCLUDE_FEATURE_SCORES;
pub const SZ_WHY_SEARCH_DEFAULT_FLAGS: i64 =
    SZ_INCLUDE_FEATURE_SCORES | SZ_SEARCH_INCLUDE_REQUEST_DETAILS | SZ_SEARCH_INCLUDE_STATS;

pub const SZ_HOW_ENTITY_DEFAULT_FLAGS: i64 = SZ_INCLUDE_FEATURE_SCORES;
pub const SZ_VIRTUAL_ENTITY_DEFAULT_FLAGS: i64 = SZ_ENTITY_CORE_FLAGS;
pub const SZ_ADD_RECORD_DEFAULT_FLAGS: i64 = SZ_NO_FLAGS;
pub const SZ_DELETE_RECORD_DEFAULT_FLAGS: i64 = SZ_NO_FLAGS;
pub const SZ_RECORD_PREVIEW_DEFAULT_FLAGS: i64 = SZ_ENTITY_INCLUDE_RECORD_FEATURE_DETAILS;
pub const SZ_REEVALUATE_RECORD_DEFAULT_FLAGS: i64 = SZ_NO_FLAGS;
pub const SZ_REEVALUATE_ENTITY_DEFAULT_FLAGS: i64 = SZ_REEVALUATE_RECORD_DEFAULT_FLAGS;
pub const SZ_FIND_INTERESTING_ENTITIES_DEFAULT_FLAGS: i64 = SZ_NO_FLAGS;

// ---------------------------------------------------------------------------
// Recommended settings for searching by attributes
// ---------------------------------------------------------------------------

pub const SZ_SEARCH_BY_ATTRIBUTES_ALL: i64 = SZ_SEARCH_INCLUDE_ALL_ENTITIES
    | SZ_ENTITY_INCLUDE_REPRESENTATIVE_FEATURES
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY
    | SZ_INCLUDE_FEATURE_SCORES
    | SZ_SEARCH_INCLUDE_STATS;

pub const SZ_SEARCH_BY_ATTRIBUTES_STRONG: i64 = SZ_SEARCH_INCLUDE_RESOLVED
    | SZ_SEARCH_INCLUDE_POSSIBLY_SAME
    | SZ_ENTITY_INCLUDE_REPRESENTATIVE_FEATURES
    | SZ_ENTITY_INCLUDE_ENTITY_NAME
    | SZ_ENTITY_INCLUDE_RECORD_SUMMARY
    | SZ_INCLUDE_FEATURE_SCORES
    | SZ_SEARCH_INCLUDE_STATS;

pub const SZ_SEARCH_BY_ATTRIBUTES_MINIMAL_ALL: i64 =
    SZ_SEARCH_INCLUDE_ALL_ENTITIES | SZ_SEARCH_INCLUDE_STATS;

pub const SZ_SEARCH_BY_ATTRIBUTES_MINIMAL_STRONG: i64 =
    SZ_SEARCH_INCLUDE_RESOLVED | SZ_SEARCH_INCLUDE_POSSIBLY_SAME | SZ_SEARCH_INCLUDE_STATS;

pub const SZ_SEARCH_BY_ATTRIBUTES_DEFAULT_FLAGS: i64 = SZ_SEARCH_BY_ATTRIBUTES_ALL;
